# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Alvin-Blog
subtitle: 过程即是最好的结局
description: 世界如此之大，做一个什么样的自己完全取决于你自己的选择
author: Alvin
language: zh-Hans
timezone:

# menu
menu:
  home: /
  archives: /archives
  tags: /tags

# sitemap
sitemap:
  path: sitemap.xml


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: git@github.com:sialvsic/sialvsic.github.io.git

# my head picture
avatar: /images/avatar.jpg

# comments
duoshuo_shortname: sialvsic

# 多说分享服务
duoshuo_share: true

# Make duoshuo show UA
# user_id must NOT be null when admin_enable is true!
# you can visit http://dev.duoshuo.com get duoshuo user id.
duoshuo_info:
  ua_enable: true
  admin_enable: true
  user_id: d90080fdbf49b1cd88821e6834c9f11a
  admin_nickname: Alvin

# analytics
baidu_analytics: 10aa6be99d86164c9368d5bd303c3a93


# Social links
social:
  GitHub: https://github.com/sialvsic
  #Twitter: https://twitter.com/your-user-name
  #微博: http://weibo.com/your-user-name
  #豆瓣: http://douban.com/people/your-user-name
  #知乎: http://www.zhihu.com/people/your-user-name

# Social Icons
social_icons:
  enable: true
  # Icon Mappings
  GitHub: github
  #Twitter: twitter
  #微博: weibo

auto_excerpt:
  enable: true
  length: 150

# Local Search
# 添加百度/谷歌/本地 自定义站点内容搜索
search:
  path: search.xml
  field: post
